# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateField(auto_now_add=True, null=True)),
                ('twilio_answer', models.CharField(blank=True, max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Name',
            fields=[
                ('class_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questions_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('questions_text', models.CharField(max_length=160, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('students_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Class_Name')),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='questions_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Questions'),
        ),
        migrations.AddField(
            model_name='answers',
            name='students_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Students'),
        ),
    ]
